# Generated by Django 5.0 on 2024-05-06 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_article_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstory',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='paragraph',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
