# Generated by Django 5.0.4 on 2024-05-06 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_newsstory_subtitle_paragraph_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='incorporation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='objective',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
