# Generated by Django 5.0.4 on 2024-05-06 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_company_incorporation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launch',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_Launch', to='api.article'),
        ),
    ]
