# Generated by Django 5.0.4 on 2024-05-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_people_company_location_company_founder'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='codeveloper',
            field=models.ManyToManyField(blank=True, related_name='codevelopers_Project', to='api.company'),
        ),
        migrations.AlterField(
            model_name='project',
            name='developers',
            field=models.ManyToManyField(blank=True, related_name='developers_Project', to='api.company'),
        ),
    ]
