# Generated by Django 5.0.4 on 2024-05-08 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_project_codeveloper_alter_project_developers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='codeveloper',
            new_name='codevelopers',
        ),
    ]
