# Generated by Django 5.0.4 on 2024-05-08 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_codeveloper_project_codevelopers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='daughter_companies',
            new_name='daughter_company',
        ),
    ]
