# Generated by Django 5.0.4 on 2024-05-08 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_daughter_companies_company_daughter_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.CharField(blank=True, choices=[('general', 'general'), ('company', 'company'), ('project', 'project'), ('launch', 'launch'), ('technology', 'technology')], max_length=20),
        ),
    ]
