# Generated by Django 5.0.4 on 2024-05-11 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_launch_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='capital',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_Capital', to='api.article'),
        ),
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.CharField(blank=True, choices=[('general', 'general'), ('company', 'company'), ('project', 'project'), ('launch', 'launch'), ('technology', 'technology'), ('capital', 'caapital')], max_length=20),
        ),
        migrations.AlterField(
            model_name='launch',
            name='status',
            field=models.CharField(blank=True, choices=[('completed', 'completed'), ('ongoing', 'ongoing'), ('failed', 'failed'), ('planned', 'planned'), ('proposed', 'proposed')], max_length=100),
        ),
    ]
