# Generated by Django 5.0.4 on 2024-05-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_capital_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='capital',
            name='daughter_capital',
            field=models.ManyToManyField(blank=True, related_name='daughter_capital_Capital', to='api.capital'),
        ),
        migrations.AddField(
            model_name='capital',
            name='parent_capital',
            field=models.ManyToManyField(blank=True, related_name='parent_capital_Capital', to='api.capital'),
        ),
    ]
