# Generated by Django 5.0.4 on 2024-05-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_capital_daughter_capital_capital_parent_capital'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='capital',
            name='status',
            field=models.CharField(blank=True, choices=[('delievered', 'delievered'), ('inprocess', 'inprocess'), ('announced', 'announced'), ('rumored', 'rumored'), ('canceled', 'canceled')], max_length=20),
        ),
    ]
