# Generated by Django 5.0.4 on 2024-05-14 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_reference_name_alter_capital_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='capital',
            field=models.ManyToManyField(related_name='capital_Article', to='api.capital'),
        ),
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.CharField(blank=True, choices=[('general', 'general'), ('company', 'company'), ('project', 'project'), ('launch', 'launch'), ('technology', 'technology'), ('capital', 'capital')], max_length=20),
        ),
    ]
