# Generated by Django 5.0.4 on 2024-05-14 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_article_capital_alter_article_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='capital',
        ),
    ]
