# Generated by Django 4.2.2 on 2024-05-31 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_launch_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitaltocomapny',
            name='amount',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
