# Generated by Django 4.2.2 on 2024-06-02 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_company_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capital',
            name='amount',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='capitaltolaunch',
            name='amount',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='capitaltoprobe',
            name='amount',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='capitaltoproject',
            name='amount',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='capitaltotechnology',
            name='amount',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='probe',
            name='mass',
            field=models.BigIntegerField(blank=True),
        ),
    ]
