# Generated by Django 4.2.2 on 2024-06-05 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_capital_amount_alter_capitaltolaunch_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeEmbed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='video',
            field=models.ManyToManyField(blank=True, related_name='video_YoutubeEnbed', to='api.youtubeembed'),
        ),
    ]
